### ISSUE TITLE
Consider MIT license

### ISSUE THREAD

**Issue by lu-zen** [dan-js/use-ab-test#7]
Hello, first thanks for your awesome work.

Are you considering changing to a less restrictive license like MIT or Apache v2?

**Comment by dan-js** [comment]
Hey @lu-zen! Thank you and no problem, it's those sort of comments that continue to motivate me to maintain and improve!

Yes, I've been able to make the license MIT, which is now available in the new `1.3.0` NPM release 😄  https://www.npmjs.com/package/use-ab-test/v/1.3.0 

Hope that helps you out in some way! Please feel free to close the issue if that's all you needed

**Comment by lu-zen** [comment]
Thanks!
